name: ESLint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  eslint:
    name: Code style scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./package.json
          node-version-file: .nvmrc
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Check with ESLint
        run: yarn eslint:check
      - name: Check with Prettier
        run: yarn prettier:check

      # Once Sarif is supported in ESLint 9, for CodeQL support.
      # - name: Run ESLint
      #   env:
      #     SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
      #   run: npx eslint .
      #     --config .eslintrc.js
      #     --ext .js,.jsx,.ts,.tsx
      #     --format @microsoft/eslint-formatter-sarif
      #     --output-file eslint-results.sarif
      #   continue-on-error: true

      # - name: Upload analysis results to GitHub
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: eslint-results.sarif
      #     wait-for-processing: true
